"use client";

import React from "react";
import { ResearchResult } from "../../types/research";

interface EvaluationTabProps {
  result: ResearchResult;
}

export function EvaluationTab({ result }: EvaluationTabProps) {
  const ev = result.evaluation || {};

  if (!ev || ev.error) {
    return (
      <div className="p-4 border border-red-custom/25 bg-red-dim rounded-lg text-xs text-red-light leading-relaxed">
        <strong>Evaluation Did Not Complete</strong>
        <p className="mt-1">{ev?.error || "No evaluation metrics were generated by the evaluator agent."}</p>
      </div>
    );
  }

  const overall = Number(ev.overall_score || 0);
  const verdict = ev.verdict || "No verdict available.";

  // Score colors helper
  const getScoreColor = (val: number) => {
    if (val >= 8.5) return "#4ade80"; // green-light
    if (val >= 7.0) return "#22c55e"; // green
    if (val >= 5.0) return "#fbbf24"; // amber-light
    return "#ef4444"; // red
  };

  const ringColor = getScoreColor(overall);

  // Dimension details
  const dims = [
    { label: "Relevance", val: Number(ev.relevance_score || 0) },
    { label: "Coverage", val: Number(ev.coverage_score || 0) },
    { label: "Synthesis", val: Number(ev.synthesis_score || 0) },
    { label: "Citations", val: Number(ev.citation_score || 0) },
  ];

  return (
    <div className="flex flex-col gap-6 animate-fade-in-up max-h-[70vh] overflow-y-auto pr-1">
      {/* Overall Score Row */}
      <div className="flex flex-col sm:flex-row items-center gap-6 p-5 bg-bg-card border border-border-subtle rounded-xl shadow-sm">
        {/* SVG Score Ring */}
        <div className="relative w-24 h-24 flex items-center justify-center flex-shrink-0">
          <svg className="w-full h-full transform -rotate-95" viewBox="0 0 100 100">
            {/* Background Circle */}
            <circle
              cx="50"
              cy="50"
              r="42"
              stroke="#1e1e30"
              strokeWidth="8"
              fill="transparent"
            />
            {/* Foreground Score Path */}
            <circle
              cx="50"
              cy="50"
              r="42"
              stroke={ringColor}
              strokeWidth="8"
              fill="transparent"
              strokeDasharray={2 * Math.PI * 42}
              strokeDashoffset={2 * Math.PI * 42 * (1 - overall / 10)}
              strokeLinecap="round"
              className="transition-all duration-1000 ease-out"
            />
          </svg>
          {/* Core Text Label */}
          <div className="absolute inset-0 flex flex-col items-center justify-center font-sans select-none">
            <span
              style={{ color: ringColor }}
              className="text-2xl font-bold tracking-tight"
            >
              {overall.toFixed(1)}
            </span>
          </div>
        </div>

        {/* Verdict Details */}
        <div className="flex-1 flex flex-col text-center sm:text-left">
          <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">
            Overall Score Verdict
          </span>
          <p className="text-sm font-semibold text-white mt-1 leading-normal">
            {verdict}
          </p>
        </div>
      </div>

      {/* Dimension Scores Progress list */}
      <div>
        <h3 className="text-xs font-bold text-text-muted uppercase tracking-wider mb-3">
          Dimension Scores
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 p-4 bg-bg-card/45 border border-border-subtle rounded-xl">
          {dims.map((dim) => {
            const barColor = getScoreColor(dim.val);
            const pct = dim.val * 10;
            return (
              <div key={dim.label} className="flex flex-col gap-1.5">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-semibold text-text-primary">{dim.label}</span>
                  <span style={{ color: barColor }} className="font-mono font-bold">
                    {dim.val.toFixed(1)}
                  </span>
                </div>
                <div className="h-2 w-full bg-bg-deep border border-border-subtle rounded-full overflow-hidden">
                  <div
                    style={{
                      width: `${pct}%`,
                      backgroundColor: barColor,
                    }}
                    className="h-full rounded-full transition-all duration-700 ease-out"
                  />
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Strengths & Weaknesses 2-Column Split */}
      <hr className="border-border-subtle" />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <div>
          <h3 className="text-xs font-bold text-text-muted uppercase tracking-wider mb-3 flex items-center gap-1.5">
            <span className="text-green-light">✓</span> Strengths
          </h3>
          <ul className="flex flex-col gap-3 p-4 bg-green-dim/10 border border-green-light/10 rounded-xl">
            {ev.strengths && ev.strengths.length > 0 ? (
              ev.strengths.map((str, idx) => (
                <li key={idx} className="flex gap-2.5 items-start text-xs text-text-secondary leading-relaxed">
                  <span className="text-green-light font-bold">✓</span>
                  <div>{str}</div>
                </li>
              ))
            ) : (
              <li className="text-xs text-text-muted italic">None recorded.</li>
            )}
          </ul>
        </div>

        {/* Weaknesses */}
        <div>
          <h3 className="text-xs font-bold text-text-muted uppercase tracking-wider mb-3 flex items-center gap-1.5">
            <span className="text-red-light">✗</span> Weaknesses
          </h3>
          <ul className="flex flex-col gap-3 p-4 bg-red-dim/10 border border-red-light/10 rounded-xl">
            {ev.weaknesses && ev.weaknesses.length > 0 ? (
              ev.weaknesses.map((weak, idx) => (
                <li key={idx} className="flex gap-2.5 items-start text-xs text-text-secondary leading-relaxed">
                  <span className="text-red-light font-bold">✗</span>
                  <div>{weak}</div>
                </li>
              ))
            ) : (
              <li className="text-xs text-text-muted italic">None recorded.</li>
            )}
          </ul>
        </div>
      </div>

      {/* Suggestions block */}
      {ev.improvement_suggestions && ev.improvement_suggestions.length > 0 && (
        <>
          <hr className="border-border-subtle" />
          <div>
            <h3 className="text-xs font-bold text-text-muted uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <span className="text-accent-light">→</span> Improvement Suggestions
            </h3>
            <ul className="flex flex-col gap-3 p-4 bg-accent-dim/10 border border-accent/10 rounded-xl">
              {ev.improvement_suggestions.map((sug, idx) => (
                <li key={idx} className="flex gap-2.5 items-start text-xs text-text-secondary leading-relaxed">
                  <span className="text-accent-light font-bold">→</span>
                  <div>{sug}</div>
                </li>
              ))}
            </ul>
          </div>
        </>
      )}
    </div>
  );
}
