from __future__ import annotations
from typing import TypedDict
from pydantic import BaseModel, Field

class PaperMeta(TypedDict):
    """Metadata for a single discovered research paper."""
    title: str
    url: str
    snippet: str
    relevance_note: str   # extraction agent's one-line relevance judgement
    publication_year: int | None
    authors: str | None
    citation_count: int | None


class AgentState(TypedDict):
    """
    Canonical state object passed between all graph nodes.
    Every field has a clear owner and lifecycle.
    """
    # ── Inputs 
    topic: str                          # Original user-supplied research topic

    # ── Discovery node output 
    search_queries: list[str]           # Queries generated by discovery agent
    discovered_papers: list[PaperMeta] # Papers found (title, url, snippet)
    discovery_raw: str                  # Raw search output (for debugging)

    # ── Extraction node output 
    extracted_contexts: list[dict]      # Per-paper: {url, content, key_points, citations}
    extraction_errors: list[str]        # URLs that failed to extract

    # ── Writer node output 
    draft_report: str                   # Full synthesised research report

    # ── Evaluator node output 
    evaluation: dict                    # Structured score + feedback

    # ── Control flow 
    retry_count: int                    # How many times discovery has been retried
    error_log: list[str]                # Pipeline-level errors (non-fatal)


class DiscoveryOutput(BaseModel):
    """Expected JSON structure from the discovery agent."""
    search_queries: list[str] = Field(
        description="2–4 refined search queries to find the most relevant papers",
        min_length=1,
    )
    papers: list[dict] = Field(
        description="List of papers with keys: title, url, snippet, relevance_note"
    )


class ExtractionOutput(BaseModel):
    """Expected JSON structure from the extraction agent for one paper."""
    url: str
    content_summary: str = Field(description="300–500 word summary of the paper's content")
    key_points: list[str] = Field(description="5–8 most important findings or claims")
    methodology: str = Field(description="Brief description of research methodology used")
    citations: list[str] = Field(description="Any citations or references found in the text")
    relevance_to_topic: str = Field(description="Explicit explanation of how this paper relates to the research topic")


class EvaluationOutput(BaseModel):
    """Structured evaluation score from the evaluator agent."""
    relevance_score: int = Field(ge=0, le=10, description="How relevant are the papers to the topic (0–10)")
    coverage_score: int = Field(ge=0, le=10, description="How well the topic is covered (0–10)")
    synthesis_score: int = Field(ge=0, le=10, description="Quality of the written report (0–10)")
    citation_score: int = Field(ge=0, le=10, description="Are all claims backed by sources (0–10)")
    recency_score: int = Field(ge=0, le=10, description="Recency of the paper publications and references (0–10)")
    overall_score: float = Field(description="Weighted average of all scores")
    strengths: list[str] = Field(description="What the pipeline did well")
    weaknesses: list[str] = Field(description="Where it fell short")
    improvement_suggestions: list[str] = Field(description="Specific, actionable suggestions")
    verdict: str = Field(description="One-sentence overall verdict")
